# Generated by Django 4.0.4 on 2022-05-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispy_htmx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subject',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Web Development'), (2, 'Systems Programming'), (3, 'Data Science')], null=True),
        ),
    ]
